import type { Project, User, Message, Part } from '@/types'

export const mockUser: User = {
  id: 'user-1',
  email: 'olly@example.com',
  username: 'olly',
  credits: 8,
  plan: 'free',
}

export const mockProject: Project = {
  id: 'project-1',
  name: 'Garbage Robot',
  description:
    'This autonomous refuse bot navigates with a front ultrasonic sensor and vision camera, driven by two stepper motors controlled by an L298N driver. A lid actuator servo opens the refuse container, all powered by a 12V LiPo battery and managed by a Raspberry Pi controller with voice output.',
  status: 'published',
  author: 'olly',
  createdAt: '2026-04-05T00:00:00.000Z',
  updatedAt: '2026-04-05T00:00:00.000Z',
  totalCost: 311.15,
  parts: [
    {
      id: 'part-1',
      name: 'Raspberry Pi 4 Model B',
      category: 'mcu',
      model: 'Raspberry Pi 4 Model B',
      description: 'Main controller - Single-board computer for processing, vision, and LLM access.',
      qty: 1,
      unitCost: 55.0,
      amazonAsin: 'B08DJD7CWT',
    },
    {
      id: 'part-2',
      name: 'HC-SR04 Ultrasonic Sensor',
      category: 'sensor',
      model: 'HC-SR04',
      description: 'Front ultrasonic sensor - Measures distance to detect obstacles or refuse level.',
      qty: 1,
      unitCost: 3.0,
      amazonAsin: 'B07VRPC9MY',
    },
    {
      id: 'part-3',
      name: 'Raspberry Pi Camera Module 3',
      category: 'sensor',
      model: 'RPi Camera Module 3',
      description: 'Vision camera - 12MP camera for visual recognition tasks.',
      qty: 1,
      unitCost: 25.0,
      amazonAsin: 'B0BSHQ7K1X',
    },
    {
      id: 'part-4',
      name: 'NEMA 17 Stepper Motor',
      category: 'actuator',
      model: 'NEMA 17',
      description: 'Drives the left/right wheel for locomotion.',
      qty: 2,
      unitCost: 15.0,
      amazonAsin: 'B00QB3PYYQ',
    },
    {
      id: 'part-5',
      name: 'SG90 Micro Servo Motor',
      category: 'actuator',
      model: 'SG90',
      description: 'Opens and closes the robot lid.',
      qty: 1,
      unitCost: 5.0,
      amazonAsin: 'B07VRFJ5VX',
    },
    {
      id: 'part-6',
      name: '3S 12V LiPo Battery',
      category: 'power',
      model: '3S 12V 1500mAh',
      description: 'Main power source for robot components.',
      qty: 1,
      unitCost: 25.0,
      amazonAsin: 'B07RSN6HXS',
    },
    {
      id: 'part-7',
      name: 'L298N Dual H-Bridge Motor Driver',
      category: 'module',
      model: 'L298N',
      description: 'Controls direction and speed of two stepper motors.',
      qty: 1,
      unitCost: 8.0,
      amazonAsin: 'B07T5K2RK3',
    },
    {
      id: 'part-8',
      name: '2020 V-Slot Aluminum Extrusion',
      category: 'structural',
      model: '2020 300mm',
      description: '20x20mm V-slot aluminum extrusion for frame.',
      qty: 4,
      unitCost: 7.5,
      amazonAsin: 'B08FQHZQ3M',
    },
    {
      id: 'part-9',
      name: 'Small Plastic Trash Can',
      category: 'enclosure',
      model: 'Refuse Container',
      description: 'Standard small plastic refuse container.',
      qty: 1,
      unitCost: 15.0,
      amazonAsin: 'B08FQHZQ3M',
    },
    {
      id: 'part-10',
      name: 'L298N Motor Driver Mount',
      category: '3d_print',
      model: '3D Printed',
      description: 'Mounting bracket for the L298N Motor Driver.',
      qty: 1,
      unitCost: 0,
      printSpecs: {
        material: 'PLA',
        layerHeight: '0.2mm',
        infill: '15%',
      },
    },
  ],
  instructions: [
    {
      step: 1,
      title: 'Print 3D Parts',
      description: 'Print all required 3D parts before starting assembly.',
      partIds: ['part-10'],
      tools: ['3D Printer', 'PLA filament'],
    },
    {
      step: 2,
      title: 'Assemble Base Frame',
      description: 'Connect aluminum extrusions using corner brackets to form the base frame.',
      partIds: ['part-8'],
      tools: ['M4 bolts', 'M4 nuts', 'Allen key'],
      tips: 'Ensure frame is square before tightening all bolts.',
    },
    {
      step: 3,
      title: 'Install Motors',
      description: 'Mount stepper motors using 3D printed motor mounts.',
      partIds: ['part-4'],
      tools: ['M3 bolts', 'Screwdriver'],
    },
    {
      step: 4,
      title: 'Install M4 Nuts',
      description: 'Insert M4 nuts into aluminum extrusion channels for future assembly.',
      partIds: [],
      tools: [],
    },
  ],
}

export const communityProjects: Project[] = [
  {
    id: 'community-1',
    name: 'CNC Mill',
    description: 'Desktop CNC milling machine for PCB prototyping.',
    status: 'published',
    author: 'spino_afbb',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    totalCost: 420.0,
    parts: [],
  },
  {
    id: 'community-2',
    name: '7inch Drone AI',
    description: 'Autonomous drone with AI vision capabilities.',
    status: 'published',
    author: 'compso_c28',
    createdAt: '2026-03-31T00:00:00.000Z',
    updatedAt: '2026-03-31T00:00:00.000Z',
    totalCost: 580.0,
    parts: [],
  },
  {
    id: 'community-3',
    name: 'Tower Server',
    description: 'Rack-mounted home server with cooling system.',
    status: 'published',
    author: 'ptero_dbeb',
    createdAt: '2026-04-02T00:00:00.000Z',
    updatedAt: '2026-04-02T00:00:00.000Z',
    totalCost: 890.0,
    parts: [],
  },
  {
    id: 'community-4',
    name: 'ARCHI-TERRAIN 01',
    description: 'Architectural terrain model with servo-controlled elements.',
    status: 'published',
    author: 'hadro_ca6a',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    totalCost: 156.0,
    parts: [],
  },
]

export const ideaExamples = [
  '智能家居温湿度监控系统',
  '太阳能追踪器',
  '避障 autonomous robot car',
  'ESP32 网络收音机',
  'LED 矩阵信息牌',
  '履带式巡逻机器人，带摄像头和红外夜视',
  '自动浇花系统',
  '空气监测站',
]

export function getCategoryColor(category: string): string {
  const colors: Record<string, string> = {
    mcu: '#3b82f6',
    sensor: '#22c55e',
    actuator: '#f59e0b',
    power: '#ef4444',
    module: '#8b5cf6',
    structural: '#6b7280',
    enclosure: '#14b8a6',
    mechanism: '#f97316',
    misc: '#9ca3af',
    '3d_print': '#ec4899',
  }
  return colors[category] || '#9ca3af'
}

export function getCategoryLabel(category: string): string {
  const labels: Record<string, string> = {
    mcu: 'MCU',
    sensor: 'Sensor',
    actuator: 'Actuator',
    power: 'Power',
    module: 'Module',
    structural: 'Structural',
    enclosure: 'Enclosure',
    mechanism: 'Mechanism',
    misc: 'Misc',
    '3d_print': '3D Print',
  }
  return labels[category] || category
}
