import type { Project, User, Message, Part } from '@/types'

export const mockUser: User = {
  id: 'user-1',
  email: 'olly@example.com',
  username: 'olly',
  credits: 8,
  plan: 'free',
}

export const mockProject: Project = {
  id: 'project-1',
  name: 'Garbage Robot',
  description:
    'This autonomous refuse bot navigates with a front ultrasonic sensor and vision camera, driven by two stepper motors controlled by an L298N driver. A lid actuator servo opens the refuse container, all powered by a 12V LiPo battery and managed by a Raspberry Pi controller with voice output.',
  status: 'published',
  author: 'olly',
  createdAt: '2026-04-05T00:00:00.000Z',
  updatedAt: '2026-04-05T00:00:00.000Z',
  totalCost: 311.15,
  parts: [
    {
      id: 'part-1',
      name: 'Raspberry Pi 4 Model B',
      category: 'mcu',
      model: 'Raspberry Pi 4 Model B',
      description: 'Main controller - Single-board computer for processing, vision, and LLM access.',
      qty: 1,
      unitCost: 55.0,
    },
    {
      id: 'part-2',
      name: 'HC-SR04 Ultrasonic Sensor',
      category: 'sensor',
      model: 'HC-SR04',
      description: 'Front ultrasonic sensor - Measures distance to detect obstacles or refuse level.',
      qty: 1,
      unitCost: 3.0,
    },
    {
      id: 'part-3',
      name: 'Raspberry Pi Camera Module 3',
      category: 'sensor',
      model: 'RPi Camera Module 3',
      description: 'Vision camera - 12MP camera for visual recognition tasks.',
      qty: 1,
      unitCost: 25.0,
    },
    {
      id: 'part-4',
      name: 'NEMA 17 Stepper Motor',
      category: 'actuator',
      model: 'NEMA 17',
      description: 'Drives the left/right wheel for locomotion.',
      qty: 2,
      unitCost: 15.0,
    },
    {
      id: 'part-5',
      name: 'SG90 Micro Servo Motor',
      category: 'actuator',
      model: 'SG90',
      description: 'Opens and closes the robot lid.',
      qty: 1,
      unitCost: 5.0,
    },
    {
      id: 'part-6',
      name: '3S 12V LiPo Battery',
      category: 'power',
      model: '3S 12V 1500mAh',
      description: 'Main power source for robot components.',
      qty: 1,
      unitCost: 25.0,
    },
    {
      id: 'part-7',
      name: 'L298N Dual H-Bridge Motor Driver',
      category: 'module',
      model: 'L298N',
      description: 'Controls direction and speed of two stepper motors.',
      qty: 1,
      unitCost: 8.0,
    },
    {
      id: 'part-8',
      name: '2020 V-Slot Aluminum Extrusion',
      category: 'structural',
      model: '2020 300mm',
      description: '20x20mm V-slot aluminum extrusion for frame.',
      qty: 4,
      unitCost: 7.5,
    },
    {
      id: 'part-9',
      name: 'Small Plastic Trash Can',
      category: 'enclosure',
      model: 'Refuse Container',
      description: 'Standard small plastic refuse container.',
      qty: 1,
      unitCost: 15.0,
    },
    {
      id: 'part-10',
      name: 'L298N Motor Driver Mount',
      category: '3d_print',
      model: '3D Printed',
      description: 'Mounting bracket for the L298N Motor Driver.',
      qty: 1,
      unitCost: 0,
      printSpecs: {
        material: 'PLA',
        layerHeight: '0.2mm',
        infill: '15%',
      },
    },
  ],
  instructions: [
    {
      step: 1,
      title: 'Print 3D Parts',
      description: 'Print all required 3D parts before starting assembly.',
      partIds: ['part-10'],
      tools: ['3D Printer', 'PLA filament'],
    },
    {
      step: 2,
      title: 'Assemble Base Frame',
      description: 'Connect aluminum extrusions using corner brackets to form the base frame.',
      partIds: ['part-8'],
      tools: ['M4 bolts', 'M4 nuts', 'Allen key'],
      tips: 'Ensure frame is square before tightening all bolts.',
    },
    {
      step: 3,
      title: 'Install Motors',
      description: 'Mount stepper motors using 3D printed motor mounts.',
      partIds: ['part-4'],
      tools: ['M3 bolts', 'Screwdriver'],
    },
    {
      step: 4,
      title: 'Install M4 Nuts',
      description: 'Insert M4 nuts into aluminum extrusion channels for future assembly.',
      partIds: [],
      tools: [],
    },
  ],
  imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/77/20260405/c91e3fa4/3c5066b9-98ff-4a88-920a-aa16ce6dd987.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=qrjHwUJN8FZXq%2FndxUTow%2FaNhZc%3D',
  starCount: 0,
  copyCount: 0,
}

export const communityProjects: Project[] = [
  {
    id: 'community-1',
    name: 'CNC Mill',
    description: 'Desktop CNC milling machine for PCB prototyping and small part fabrication.',
    status: 'published',
    author: 'spino_afbb',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    totalCost: 420.0,
    parts: Array(41).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'structural', model: `MODEL-${i}`, qty: 1, unitCost: 10 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/66/20260405/c91e3fa4/3c5066b9-98ff-4a88-920a-aa16ce6dd987.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=qrjHwUJN8FZXq%2FndxUTow%2FaNhZc%3D',
    tags: ['Electronics', 'Mechanical'],
    starCount: 12,
    copyCount: 4,
  },
  {
    id: 'community-2',
    name: '7inch Drone AI',
    description: 'Autonomous drone with AI vision capabilities and long flight time.',
    status: 'published',
    author: 'compso_c28',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    totalCost: 580.0,
    parts: Array(30).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'actuator', model: `MODEL-${i}`, qty: 1, unitCost: 15 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/22/20260405/c91e3fa4/64c93288-c919-4794-beff-ae651e20d9da.png?Expires=1775999191&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=ycnCH6n7IZh6lbWbLdALnIqLwQM%3D',
    tags: ['Electronics', 'Mechanical', 'Prototype'],
    starCount: 33,
    copyCount: 7,
  },
  {
    id: 'community-3',
    name: 'Tower Server',
    description: 'Rack-mounted home server with dual cooling fans and hot-swap bays.',
    status: 'published',
    author: 'ptero_dbeb',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    totalCost: 890.0,
    parts: Array(21).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'mcu', model: `MODEL-${i}`, qty: 1, unitCost: 12 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/02/20260405/c91e3fa4/b8b632da-5f27-4c85-8189-3f39f978f4bf.png?Expires=1775999191&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=B0DsekPN9GiBXzOjA7GVpVr6VPQ%3D',
    tags: ['Electronics'],
    starCount: 11,
    copyCount: 2,
  },
  {
    id: 'community-4',
    name: 'ARCHI-TERRAIN 01',
    description: 'Architectural terrain model with servo-controlled landscape elements.',
    status: 'published',
    author: 'hadro_ca6a',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    totalCost: 156.0,
    parts: Array(115).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'structural', model: `MODEL-${i}`, qty: 1, unitCost: 8 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/d6/20260405/c91e3fa4/ad4b5fe1-5d78-4466-8e97-3988b3b1cd19.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=uxKE4ocJjFxFaHeDSmwvElSXr7Q%3D',
    tags: ['Mechanical', 'Prototype'],
    starCount: 4,
    copyCount: 1,
  },
  {
    id: 'community-5',
    name: 'High-Speed UAV',
    description: 'Racing quadcopter frame with carbon fiber arms and FPV camera.',
    status: 'published',
    author: 'diplo_f1b0',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    totalCost: 320.0,
    parts: Array(35).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'actuator', model: `MODEL-${i}`, qty: 1, unitCost: 9 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/55/20260405/c91e3fa4/8a0b7c3d-1e2f-4a6b-9c8d-5e7f3a2b1c0d.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=test',
    tags: ['Electronics', 'Mechanical'],
    starCount: 9,
    copyCount: 3,
  },
  {
    id: 'community-6',
    name: 'Wall-E Robot',
    description: 'Fully articulated Wall-E inspired robot with expressive LED eyes.',
    status: 'published',
    author: 'utah_e42',
    createdAt: '2026-03-27T00:00:00.000Z',
    updatedAt: '2026-03-27T00:00:00.000Z',
    totalCost: 285.0,
    parts: Array(58).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'enclosure', model: `MODEL-${i}`, qty: 1, unitCost: 7 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/11/20260405/c91e3fa4/c1d2e3f4-5a6b-7c8d-9e0f-1a2b3c4d5e6f.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=test2',
    tags: ['Electronics', 'Mechanical', 'Prototype'],
    starCount: 23,
    copyCount: 6,
  },
  {
    id: 'community-7',
    name: 'PiClaw Robot Arm',
    description: '6-DOF robot arm with precision stepper motors and gripper end-effector.',
    status: 'published',
    author: 'deinon_ffd5',
    createdAt: '2026-03-27T00:00:00.000Z',
    updatedAt: '2026-03-27T00:00:00.000Z',
    totalCost: 460.0,
    parts: Array(19).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'actuator', model: `MODEL-${i}`, qty: 1, unitCost: 20 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/44/20260405/c91e3fa4/d5e6f7a8-9b0c-1d2e-3f4a-5b6c-7d8e9f0a1b2c.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=test3',
    tags: ['Electronics', 'Mechanical'],
    starCount: 16,
    copyCount: 5,
  },
  {
    id: 'community-8',
    name: 'Polycarbonate Smartphone',
    description: 'Rugged smartphone enclosure with machined aluminum frame.',
    status: 'published',
    author: 'pachy_cc5',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    totalCost: 88.0,
    parts: Array(20).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'enclosure', model: `MODEL-${i}`, qty: 1, unitCost: 5 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/77/20260405/c91e3fa4/e4f5a6b7-8c9d-0e1f-2a3b-4c5d6e7f8a9b.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=test4',
    tags: ['Electronics', 'Mechanical'],
    starCount: 5,
    copyCount: 2,
  },
  {
    id: 'community-9',
    name: 'RC Car Model',
    description: '1:10 scale RC car with brushless motor and LiPo battery.',
    status: 'published',
    author: 'stego_e360',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    totalCost: 145.0,
    parts: Array(22).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'actuator', model: `MODEL-${i}`, qty: 1, unitCost: 8 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/88/20260405/c91e3fa4/a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=test5',
    tags: ['Electronics', 'Mechanical', 'Prototype'],
    starCount: 1,
    copyCount: 1,
  },
  {
    id: 'community-10',
    name: 'AI Sales Badge',
    description: 'E-paper name badge with AI-powered face recognition attendance.',
    status: 'published',
    author: 'spino_e70b',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    totalCost: 55.0,
    parts: Array(16).fill(null).map((_, i) => ({ id: `part-${i}`, name: `Part ${i}`, category: 'mcu', model: `MODEL-${i}`, qty: 1, unitCost: 6 })),
    imageUrl: 'https://dashscope-7c2c.oss-accelerate.aliyuncs.com/7d/99/20260405/c91e3fa4/f6a7b8c9-0d1e-2f3a-4b5c-6d7e8f9a0b1c.png?Expires=1775999216&OSSAccessKeyId=LTAI5tPxpiCM2hjmWrFXrym1&Signature=test6',
    tags: ['Electronics'],
    starCount: 2,
    copyCount: 1,
  },
]

export const ideaExamples = [
  '智能家居温湿度监控系统',
  '太阳能追踪器',
  '避障 autonomous robot car',
  'ESP32 网络收音机',
  'LED 矩阵信息牌',
  '履带式巡逻机器人，带摄像头和红外夜视',
  '自动浇花系统',
  '空气监测站',
]

export function getCategoryColor(category: string): string {
  const colors: Record<string, string> = {
    mcu: '#3b82f6',
    sensor: '#22c55e',
    actuator: '#f59e0b',
    power: '#ef4444',
    module: '#8b5cf6',
    structural: '#6b7280',
    enclosure: '#14b8a6',
    mechanism: '#f97316',
    misc: '#9ca3af',
    '3d_print': '#ec4899',
  }
  return colors[category] || '#9ca3af'
}

export function getCategoryLabel(category: string): string {
  const labels: Record<string, string> = {
    mcu: 'MCU',
    sensor: 'Sensor',
    actuator: 'Actuator',
    power: 'Power',
    module: 'Module',
    structural: 'Structural',
    enclosure: 'Enclosure',
    mechanism: 'Mechanism',
    misc: 'Misc',
    '3d_print': '3D Print',
  }
  return labels[category] || category
}
